mod seq;
mod range;
mod len;
mod join;
mod riffle;
mod repeat;
mod skip;
mod first;
mod last;
mod rev;
mod nest;
mod flatten;
mod sort;
mod sortby;
mod fold;
mod zip;
mod r#enum;
mod ddup;
mod contains;
mod index;

pub fn init(keywords: &mut crate::keywords::Keywords) {
    seq::init(keywords);
    range::init(keywords);
    len::init(keywords);
    join::init(keywords);
    riffle::init(keywords);
    repeat::init(keywords);
    skip::init(keywords);
    first::init(keywords);
    last::init(keywords);
    rev::init(keywords);
    nest::init(keywords);
    flatten::init(keywords);
    sort::init(keywords);
    sortby::init(keywords);
    fold::init(keywords);
    zip::init(keywords);
    r#enum::init(keywords);
    ddup::init(keywords);
    contains::init(keywords);
    index::init(keywords);
}
